diff --git a/Makefile b/Makefile
index 518f604..c80a5ac 100644
--- a/Makefile
+++ b/Makefile
@@ -26,8 +26,8 @@ LDFLAGS=\
 	$(CPYTHONROOT)/installs/python-$(PYVERSION)/lib/libpython$(PYMINOR).a \
   $(LZ4LIB) \
   -s "BINARYEN_METHOD='native-wasm'" \
-  -s TOTAL_MEMORY=1073741824 \
-  -s ALLOW_MEMORY_GROWTH=1 \
+  -s TOTAL_MEMORY=128MB \
+  -s ALLOW_MEMORY_GROWTH=0 \
 	-s MAIN_MODULE=1 \
 	-s EMULATED_FUNCTION_POINTERS=1 \
   -s EMULATE_FUNCTION_POINTER_CASTS=1 \
@@ -39,9 +39,6 @@ LDFLAGS=\
 	-s USE_FREETYPE=1 \
 	-s USE_LIBPNG=1 \
 	-std=c++14 \
-  -L$(wildcard $(CPYTHONROOT)/build/sqlite*/.libs) -lsqlite3 \
-  $(wildcard $(CPYTHONROOT)/build/bzip2*/libbz2.a) \
-  -lstdc++ \
   --memory-init-file 0 \
   -s "BINARYEN_TRAP_MODE='clamp'" \
   -s TEXTDECODER=0 \
@@ -75,7 +72,7 @@ build/pyodide.asm.js: src/main.bc src/jsimport.bc src/jsproxy.bc src/js2python.b
 		src/pyimport.bc src/pyproxy.bc src/python2js.bc src/python2js_buffer.bc \
 		src/runpython.bc src/hiwire.bc
 	[ -d build ] || mkdir build
-	$(CXX) -s EXPORT_NAME="'pyodide'" -o build/pyodide.asm.html $(filter %.bc,$^) \
+	$(CC) -s EXPORT_NAME="'pyodide'" -o build/pyodide.asm.html $(filter %.bc,$^) \
 	  $(LDFLAGS) -s FORCE_FILESYSTEM=1
 	rm build/pyodide.asm.html
 
